# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5431/barbershop_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

#JWT Settings
api.security.token.secret=minha-chave-secreta-muito-longa-para-a-barbearia-2026-xyz
